ApplicationDemo/ApplicationDemo/Models/Demo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ApplicationDemo.Models
{
    public class Demo
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public  int Salary { get; set; }
        public string Dept { get; set; }
    }
}

ApplicationDemo/ApplicationDemo/Models/DemoContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApplicationDemo.Models
{
    public class DemoContext:DbContext
    {
        public DemoContext(DbContextOptions<DemoContext>options):base(options)
        { }
        public DbSet<Demo> Demos { get; set; }
    }
}

ApplicationDemo/ApplicationDemo/Models/DemoService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace ApplicationDemo.Models
{
    public class DemoService:IDemo
    {
        public DemoContext Context { get; }
        public DemoService(DemoContext context)
        {
            Context = context;
        }
        public Demo AddDemo(Demo demo)
        {
            Context.Demos.Add(demo);
            Context.SaveChanges();

            return demo; 
        }

        public List<Demo> GetDemo()
        {
            return Context.Demos.ToList();
        }
        public bool Delete(int id)
        {
            if (Context.Demos.Any(e => e.Id == id))
            {
                var emp = Context.Demos.SingleOrDefault(e => e.Id == id);
                Context.Demos.Remove(emp);
                Context.SaveChanges();
                return true;
            }
            else
            {
                return false;
            }
        }

        public Demo EditById(int Id)
        {
            var emp = Context.Demos.SingleOrDefault(e => e.Id == Id);
            return emp;

        }
       public Demo UpdateDemo(Demo demo)
        {
            
            var emp = Context.Demos.SingleOrDefault(e => e.Id == demo.Id);
            emp.Name = demo.Name;
            emp.Email = demo.Email;
            emp.Salary = demo.Salary; 
            emp.Dept = demo.Dept;
            Context.Demos.Update(emp);
            Context.SaveChanges();
            return emp;
                
    
        }
    }
}

ApplicationDemo/ApplicationDemo/Models/ErrorViewModel.cs
using System;

namespace ApplicationDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ApplicationDemo/ApplicationDemo/Models/IDemo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApplicationDemo.Models
{
   public interface IDemo
    {
        
        Demo AddDemo(Demo demo);
        List<Demo> GetDemo();
        bool Delete(int id);
        Demo EditById(int id);
        Demo UpdateDemo(Demo demo);
    }
}

ApplicationDemo/ApplicationDemo/Controllers/DemoController.cs
using ApplicationDemo.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApplicationDemo.Controllers
{
    public class DemoController : Controller
    {
        public IDemo idemo { get; }
        public DemoController(IDemo _demo)
        {
            idemo = _demo;
        }
        public IActionResult Index()
        {
            var emp = idemo.GetDemo();
            return View(emp);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Demo demo)
        {
            idemo.AddDemo(demo);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var q = idemo.Delete(id);
            if(q)
            {
                ViewBag.message = "Record Delete Successfull";
            }
            else
            {
                ViewBag.message = "Record Not  Deleted ";
            }
            return RedirectToAction("Index");

        }
        public IActionResult Edit(int id)
        {
            var q = idemo.EditById(id);
            return View(q);
        }
        [HttpPost]
        public IActionResult Update(Demo demo)
        {
            idemo.UpdateDemo(demo);
            return RedirectToAction("Index");
        }
    }
}

ApplicationDemo/ApplicationDemo/Controllers/HomeController.cs
using ApplicationDemo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ApplicationDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ApplicationDemo/ApplicationDemo/Views/Demo/Create.cshtml
@model  ApplicationDemo.Models.Demo

    <div class="row">
        <div class="col-6">
            <form asp-action="Create" method="post">
                <div class="form-group">
                    <label asp-for="Name"> </label>
                    <input asp-for="Name" />

                </div>
                <div class="form-group">
                    <label asp-for="Email"> </label>
                    <input asp-for="Email" />

                </div>
                <div class="form-group">
                    <label asp-for="Salary"> </label>
                    <input asp-for="Salary" />

                </div>
                <div class="form-group">
                    <label asp-for="Dept"> </label>
                    <input asp-for="Dept" />

                </div>
                <div class="form-group">
                   
                    <input  type="submit" value="Save" class="form-control"/>

                </div>

            </form>
        </div>
    </div>

ApplicationDemo/ApplicationDemo/Views/Demo/Edit.cshtml
@model  ApplicationDemo.Models.Demo

<div class="row">
    <div class=" col-6">
        <form asp-controller="Demo" asp-action="Update" method="post">

            <div class="form-group">
                
                <input type="hidden" asp-for="Id" />
            </div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input type="text" asp-for="Name" />
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input type="text" asp-for="Email" />
            </div>
            <div class="form-group">
                <label asp-for="Salary"></label>
                <input type="text" asp-for="Salary" />
            </div>
            <div class="form-group">
                <label asp-for="Dept"></label>
                <input type="text" asp-for="Dept" />
            </div>
            <div class="form-group">

                <input type="submit" value="Update" class="btn btn-primery btn-block" />
            </div>



        </form>

    </div>
</div>

ApplicationDemo/ApplicationDemo/Views/Demo/Index.cshtml
@model IEnumerable<ApplicationDemo.Models.Demo>

<a asp-controller="Demo" asp-action="Create">Create</a>
<div class="row">
    <div class="col-12 ">
        <table class="table table-bordered" >
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Salary</th>
                <th>Dept</th>
            </tr>

            @foreach (var em in Model)
            {
        <tr>
            <td>@em.Id</td>
            <td>@em.Name</td>
            <td>@em.Email</td>
            <td>@em.Salary</td>
            <td>@em.Dept</td>
            
            <td><a asp-controller="Demo" asp-action="Edit" asp-route-id="@em.Id">Edit</a></td>
            <td><a asp-controller="Demo" asp-action="Delete" asp-route-id="@em.Id">Delete</a></td>
        </tr>
                    }
               
            </table>
    </div>
</div>

ApplicationDemo/ApplicationDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ApplicationDemo/ApplicationDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ApplicationDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ApplicationDemo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ApplicationDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>